variables:
    php: docker exec -it -w /var/www/html tournidel_php

commands:
    start:
        help: Start docker compose
        steps:
            - docker-compose up -d

    stop:
        help: Stop docker compose
        steps:
            - docker-compose stop

    bash:
        help: Login to PHP container
        steps:
            - ${php} bash

    quality:
        help: Run all quality jobs
        steps:
            - ${php} php-cs-fixer fix --config=.php_cs.dist
            - ${php} vendor/bin/phpstan analyse src/ --level 5

    assets:
        help: Run assets watch
        steps:
            - ${php} yarn watch

    install:
        help: Install project
        steps:
            # PHP dependencies
            - ${php} composer2 install

            # Migrations & Fixtures
            - ${php} ./bin/console doctrine:migrations:migrate --no-interaction
            - ${php} ./bin/console doctrine:fixtures:load --no-interaction

            # Assets
            - ${php} yarn install
            - ${php} yarn dev

    test:
        help: Test command
        steps:
            - echo "coucou"
