commands:
    fmt:
        help: Checking formatting
        steps:
            - gofmt -s -w .

    test: 
        help: Running tests
        steps:
            - go test -cover ./...

    clean_deps:
        help: Clean unused dependencies
        steps:
            - go mod tidy

    update_deps:
        help: Upgrade dependencies
        steps:
            - go get -t -u -v ./...