before:
  hooks:
    - go mod download

builds:
  -
    id: macos
    goos: [darwin]
    goarch: [amd64]
    binary: bin/ae
    ldflags:
      - -s -w -X main.Version={{ .Version }}
  -
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    binary: bin/ae
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0

archives:
  - 
    format: gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
