before:
  hooks:
    - go mod download

builds:
  -
    id: macos
    goos: [darwin]
    goarch: [amd64]
    binary: bin/ae
    main: ./cmd/ae
    ldflags:
      - -s -w -X github.com/iq2i/aergie/internal/build.Version={{ .Version }} -X github.com/iq2i/aergie/internal/build.Date={{ time "2006-01-02 15:04:05" }}
  -
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    binary: bin/ae
    main: ./cmd/ae
    ldflags:
      - -s -w -X github.com/iq2i/aergie/internal/build.Version={{ .Version }} -X github.com/iq2i/aergie/internal/build.Date={{ time "2006-01-02 15:04:05" }}
    env:
      - CGO_ENABLED=0

archives:
  - 
    format: gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - ../../LICENSE
      - ../../README.md

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
