before:
  hooks:
    - go mod download

builds:
  - 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - 
        goos: darwin
        goarch: 386
      - 
        goos: darwin
        goarch: arm
      - 
        goos: darwin
        goarch: arm64

archives:
  - 
    format: gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - ../../LICENSE
      - ../../README.md

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
