name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CGO_ENABLED: '0' # https://github.com/golang/go/issues/26988
  GO111MODULE: 'on'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - 
        name: Project dependencies
        run: go get -d -u ./...
      - 
        name: Test
        run: go test ./...