name: "Continuous Integration"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CGO_ENABLED: '0' # https://github.com/golang/go/issues/26988
  GO111MODULE: 'on'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  tests:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Project dependencies
        run: go get -d -u ./...
      - name: Test
        run: go test -covermode atomic -coverprofile=profile.cov ./...
      - name: Upload coverage results
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github